server:
  port: 8081
spring:
  application:
    name: springbootcards01
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

